name: delivery_knight_restaurant
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  cupertino_icons: ^1.0.2
  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  image_picker: ^0.8.4+9
  firebase_storage: ^10.2.7






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0



flutter:

  uses-material-design: true


  assets:
    - assets/

