name: deliveryknight
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.0.2
  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  fluttertoast: ^8.0.8
  sn_progress_dialog: ^1.0.3
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  flutter_spinkit: ^5.1.0
  flutter_custom_clippers: ^2.0.0
  cached_network_image: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
flutter_native_splash:

  background_image: "assets/splash.png"
  android: true
  ios: true
  image: assets/logo.png

